### ISSUE TITLE
Is initialization meant to take this long?

### ISSUE THREAD

**Issue by lplawlor** [cachix/devenv#1047] opened 2024-03-25 03:04 UTC
I am just starting with devenv, on a NixOS WSL system defined in a flake. I'm following the [Getting Started](https://devenv.sh/getting-started/) page on the devenv site.

I've installed devenv and direnv to my system packages. I typically use the nixos-23.11 version of nixpkgs, but it looks like [devenv was just added a few days ago to nixos-unstable](https://github.com/NixOS/nixpkgs/commits/nixos-unstable/pkgs/by-name/de/devenv/package.nix), so I had to install it using an overlay. This is besides the point of my post really, but I think it would be worth mentioning on the Getting Started page that devenv isn't in the stable branch yet.

After running nixos-rebuild to install devenv, I entered a new directory and ran `devenv init`, which created the new devenv files and (because of direnv) started up the shell right away. However, the installation is taking a **long** time. It's been probably around 15 minutes, and I'm still building packages. A snapshot of the status indicator:

```
[2/47/246 built, 178 copied (987.2/987.8 MiB), 475.0 MiB DL]  building cmake-minimal-3.28.3 (configurePhase): g++ -Wno-elaborated-enum-base 
```

I get the same result when, instead of using direnv for automatic shell activation, I run `devenv shell`.

I can't imagine the initialization process is meant to take this long, is it?

**Comment by domenkozar** [comment] 2024-03-25 06:07
What's the output of `nix store ping`?

**Comment by lplawlor** [comment] 2024-03-25 11:10
> What's the output of `nix store ping`?

```
~❯ nix store ping
Store URL: daemon
Version: 2.18.1
Trusted: 0
```

**Comment by ricoschouten** [comment] 2024-03-25 11:40
> What's the output of `nix store ping`?

```bash
$ nix store info
Store URL: daemon
Version: 2.20.5
Trusted: 0
```

The `cmake-minimal-3.28.3` was taking a long time for me as well, so I left it to run overnight.

Currently stuck on:

```bash
[0/559 built] waiting for lock on '/nix/store/37dl1ra63g3a0ns8c0rr7w0w85ipmwyb-llvm-16.0.6-lib', '/nix/store/8l317zwdhpqh0yq5b99czchcgj9rdx9p-llvm-16.0.6', '/nix/store/f1im8z3jl8hiligklm1l8ms6mh63nlp7-llvm-16.0.6-python', '/nix/store/f53445125j5h9i3rxjcdqn0092lpc8vx-llvm-16.0.6-dev'
```

Might be because my system suspended while evaluating the derivation.

**Comment by domenkozar** [comment] 2024-03-25 11:42
This is a duplicate of https://github.com/cachix/devenv/issues/1043, let's keep all the discussion there.

**Closed by domenkozar** 2024-03-25 11:42 UTC
Labels: question
