### ISSUE TITLE
devenv causing issues when running `phx.new`

### ISSUE THREAD

**Issue by multivac61** [cachix/devenv#1577] opened 2024-11-06 17:28 UTC
**Describe the bug**
Following the [phoenix example](https://github.com/cachix/devenv/tree/main/examples/phoenix) tailwindcss lsp in `phx new --install .` should work the same as `phx new --install hello && cd hello`

See issue created in the phoenix repo: https://github.com/phoenixframework/phoenix/issues/5967

**To reproduce**

Try creating a blank phoenix project using

https://github.com/multivac61/phx_devenv 

with a) the direnv devshell and b) `nix shell nixpkgs#elixir`. The latter one works fine.

**Version**
 
Paste the output of `$ devenv version` here or tell us if you're using flakes.

using flakes, `devenv: 1.3.1`

**Comment by multivac61** [comment] 2024-11-06 17:59
Ugh, this turned out to be an implementation detail of direnv: https://github.com/direnv/direnv/wiki/Customizing-cache-location

**Comment by multivac61** [comment] 2024-11-06 18:25
Ah.. it also doesn't like having the `.devenv/` folder there either...

**Comment by multivac61** [comment] 2024-11-07 12:33
The issue is circumvented by setting

```nix
enterShell = "export DEVENV_DOTFILE=$(mktemp -d)";
```

**Comment by multivac61** [comment] 2024-11-07 13:15
or by setting `devenv.dotfile = "/tmp/devenv-" + baseNameOf ./.;` in the `flake.nix`

**Comment by sandydoo** [comment] 2024-11-07 13:33
Got around to testing this. I think it's duplicate of #1569. The PR causing issues was reverted in #1576.

**Comment by multivac61** [comment] 2024-11-07 17:03
Confirm it works with revert.

**Comment by sandydoo** [comment] 2024-11-07 20:58
Resolved by #1576.

**Closed by sandydoo** 2024-11-07 20:58 UTC
Labels: bug
