### ISSUE TITLE
Installation takes a long time

### ISSUE THREAD

**Issue by khaled** [cachix/devenv#536] opened 2023-04-18 00:49 UTC
**Describe the bug**

Installation of devenv is slow, AFAICT because aws-sdk-cpp and nix-2.12.0pre are built from source rather than pulled from cache.

**To Reproduce**

The steps below are run in the official nix docker container, though I've observed the same behavior on aarch64-darwin (locally), and on aarch64-linux (a VM):

```
❯ docker run --rm -it nixos/nix

bash-5.1# nix --version
nix (Nix) 2.15.0
bash-5.1# nix-env -iA cachix -f https://cachix.org/api/v1/install
installing 'cachix-1.3.3'
copying path '/nix/store/9q7vpjglay90dbmck8aari340vhiw3yg-busybox-static-aarch64-unknown-linux-musl-1.36.0' from 'https://cache.nixos.org'...
...

bash-5.1# cachix use devenv
Configured https://devenv.cachix.org binary cache in /etc/nix/nix.conf

bash-5.1# nix-env -if https://github.com/cachix/devenv/tarball/latest
installing 'devenv'
these 10 derivations will be built:
  /nix/store/9qcrqk3v6d94xwwxbxpxfxbs07nmryz1-libzip-1.9.2.drv
  /nix/store/w9g502p59yp1fn2dljmvnnhans3rq9b4-aws-sdk-cpp-1.9.294.drv
...

building '/nix/store/w9g502p59yp1fn2dljmvnnhans3rq9b4-aws-sdk-cpp-1.9.294.drv'...
unpacking sources
unpacking source archive /nix/store/26lg59zjav1irl0znfx5rx3liv47n1r7-source
source root is source
patching sources
applying patch /nix/store/frvfi397b88f6c91p371z5r2940x005p-cmake-dirs.patch
patching file cmake/AWSSDKConfig.cmake
...

building '/nix/store/00dk0qx5vjl9bywy5db593a2dfdzd66f-nix-2.12.0pre20230216_7c91803.drv'...
unpacking sources
unpacking source archive /nix/store/isia7synl0mdbcvfwav5ywnrwmwbwvxv-source
source root is source
...

```

**Version**
`devenv: 0.6.2`

**Comment by domenkozar** [comment] 2023-04-20 11:11
That's why there's a step (2) in the installation to configure devenv cachix.

**Comment by khaled** [comment] 2023-04-22 02:42
@domenkozar I did perform that step, as illustrated in the log I shared :).  The source builds of aws-sdk-cpp and nix happen regardless.

**Comment by darkone23** [comment] 2023-04-26 16:18
Also saw this behavior installing last night. Setup cache using `cachix use devenv` - basic flake sample:

```

{
  description = "build flake";

  inputs = {

    nixpkgs.url = "github:nixos/nixpkgs/nixos-unstable";

    home-manager.url = "github:nix-community/home-manager";
    home-manager.inputs.nixpkgs.follows = "nixpkgs";

    devenv.url = "github:cachix/devenv/latest";
    devenv.inputs.nixpkgs.follows = "nixpkgs";
    
  };

  outputs = { self, nixpkgs, home-manager, devenv, ... }:
    nixosConfigurations.myhost = nixpkgs.lib.nixosSystem {
      system = "x86_64-linux";
      modules = [ 
        ./configuration.nix
        {
          environment.systemPackages = [
            devenv.packages.x86_64-linux.devenv
          ];
        }
        home-manager.nixosModules.home-manager
          {
            home-manager.useGlobalPkgs = true;
            home-manager.useUserPackages = true;
            home-manager.users.myuser = import ./home.nix;
          }
      ];
    };

}

```

built just fine, just had to build from source like described

**Comment by domenkozar** [comment] 2023-04-26 17:05
Most likely due to CI failing fast, I've pushed https://github.com/cachix/devenv/commit/47eb4d1f12a9209913a485f9df945c2a404a918a that should address it.

**Comment by sandydoo** [comment] 2023-04-29 15:28
@domenkozar, devenv doesn't have builds for `aarch64-linux`, right? That would explain the build from source. `aarch64-darwin` should've been cached though, unless this builder isn't `aarch64`?

@darkone23, what system are you using?

**Comment by mausch** [comment] 2023-05-09 10:53
Related: https://github.com/cachix/devenv/issues/575

**Comment by Nick1296** [comment] 2023-05-17 20:23
I can confirm that this happens on `aarch64-linux` (my raspberrypi) after following both the instruction of #575 and the instructions after `cachix use devenv`. How do I check if there are cached builds?

**Comment by domenkozar** [comment] 2023-05-18 11:18
We'll setup an aarch64-linux builder

**Comment by domenkozar** [comment] 2023-06-08 08:35
I've added aarch64-linux builder in https://github.com/cachix/devenv/pull/652

**Comment by AnhQuanTrl** [comment] 2023-11-19 17:07
Happens for me as well. I am on x86_64-linux and it try to rebuild everything from source even though cachix is already installed :(

**Comment by sandydoo** [comment] 2023-11-25 15:02
@domenkozar, could some of the releases have been GC'd from the cache? We should pin them!

**Comment by shyim** [comment] 2024-03-28 09:57
I think this can be closed as we moved to nixpkgs right? @domenkozar

**Closed** 2024-04-01 06:41 UTC
Labels: bug
