### ISSUE TITLE
Clean devenv does not support process-compose

### ISSUE THREAD

**Issue by Enteee** [cachix/devenv#1492] opened 2024-10-02 11:23 UTC
**Describe the bug**
process compose does not work in a `clean.enabled = true` devenv.

```bash
$ devenv  up
• Building processes ...
• Using Cachix: devenv
✔ Building processes in 7.1s.
• Starting processes ...
• Building shell ...
✔ Building shell in 1.5s.
Running tasks     devenv:enterShell
Succeeded         devenv:enterShell 2ms
1 Succeeded                         2.49ms

{"level":"warn","error":"open /etc/xdg/process-compose/settings.yaml: no such file or directory","time":"2024-10-02T13:21:59+02:00","message":"Error reading settings file /etc/xdg/process-compose/settings.yaml"}
panic: exec: "infocmp": executable file not found in $PATH

goroutine 9 [running]:
github.com/f1bonacc1/process-compose/src/tui.SetupTui({0xe9e960?, 0xc000127ea0?}, {0xc000051f78, 0x3, 0xc000140640?})
	github.com/f1bonacc1/process-compose/src/tui/view.go:505 +0x156
github.com/f1bonacc1/process-compose/src/cmd.startTui({0xe9e960, 0xc000127ea0})
	github.com/f1bonacc1/process-compose/src/cmd/project_runner.go:89 +0x1d5
created by github.com/f1bonacc1/process-compose/src/cmd.runTui in goroutine 1
	github.com/f1bonacc1/process-compose/src/cmd/project_runner.go:73 +0x65
```

**To reproduce**

Run `devenv up` with the following configuration:

* `devenv.yaml`

```yml
# yaml-language-server: $schema=https://devenv.sh/devenv.schema.json
clean:
  enabled: true

inputs:
  nixpkgs:
    url: github:cachix/devenv-nixpkgs/rolling
```

* `devenv.nix`
```nix
{ pkgs, lib, config, inputs, ... }:

{
  packages = with pkgs; [
    coreutils
  ];

  processes.uname.exec = "uname";
}
```

* `devenv.lock`
```json
{
  "nodes": {
    "devenv": {
      "locked": {
        "dir": "src/modules",
        "lastModified": 1727779147,
        "owner": "cachix",
        "repo": "devenv",
        "rev": "eb86c60fc04a8be6a544b2647cc0ca8dc611533e",
        "type": "github"
      },
      "original": {
        "dir": "src/modules",
        "owner": "cachix",
        "repo": "devenv",
        "type": "github"
      }
    },
    "flake-compat": {
      "flake": false,
      "locked": {
        "lastModified": 1696426674,
        "owner": "edolstra",
        "repo": "flake-compat",
        "rev": "0f9255e01c2351cc7d116c072cb317785dd33b33",
        "type": "github"
      },
      "original": {
        "owner": "edolstra",
        "repo": "flake-compat",
        "type": "github"
      }
    },
    "gitignore": {
      "inputs": {
        "nixpkgs": [
          "pre-commit-hooks",
          "nixpkgs"
        ]
      },
      "locked": {
        "lastModified": 1709087332,
        "owner": "hercules-ci",
        "repo": "gitignore.nix",
        "rev": "637db329424fd7e46cf4185293b9cc8c88c95394",
        "type": "github"
      },
      "original": {
        "owner": "hercules-ci",
        "repo": "gitignore.nix",
        "type": "github"
      }
    },
    "nixpkgs": {
      "locked": {
        "lastModified": 1716977621,
        "owner": "cachix",
        "repo": "devenv-nixpkgs",
        "rev": "4267e705586473d3e5c8d50299e71503f16a6fb6",
        "type": "github"
      },
      "original": {
        "owner": "cachix",
        "ref": "rolling",
        "repo": "devenv-nixpkgs",
        "type": "github"
      }
    },
    "nixpkgs-stable": {
      "locked": {
        "lastModified": 1727672256,
        "owner": "NixOS",
        "repo": "nixpkgs",
        "rev": "1719f27dd95fd4206afb9cec9f415b539978827e",
        "type": "github"
      },
      "original": {
        "owner": "NixOS",
        "ref": "nixos-24.05",
        "repo": "nixpkgs",
        "type": "github"
      }
    },
    "pre-commit-hooks": {
      "inputs": {
        "flake-compat": "flake-compat",
        "gitignore": "gitignore",
        "nixpkgs": [
          "nixpkgs"
        ],
        "nixpkgs-stable": "nixpkgs-stable"
      },
      "locked": {
        "lastModified": 1727854478,
        "owner": "cachix",
        "repo": "pre-commit-hooks.nix",
        "rev": "5f58871c9657b5fc0a7f65670fe2ba99c26c1d79",
        "type": "github"
      },
      "original": {
        "owner": "cachix",
        "repo": "pre-commit-hooks.nix",
        "type": "github"
      }
    },
    "root": {
      "inputs": {
        "devenv": "devenv",
        "nixpkgs": "nixpkgs",
        "pre-commit-hooks": "pre-commit-hooks"
      }
    }
  },
  "root": "root",
  "version": 7
}
```

**Version**
 
`devenv 1.2.0 (x86_64-linux)`

**Comment by sandydoo** [comment] 2024-10-02 11:29
I keep forgetting to add guidance about this to the docs 🤦 `clean` completely nukes the shell environment. You absolutely must use `keep` to bring it back to a working state. It's best not to use this feature at all.

Closing as duplicate of https://github.com/cachix/devenv/issues/1163.

**Closed by sandydoo** 2024-10-02 11:29 UTC
Labels: bug

**Comment by Enteee** [comment] 2024-10-02 11:34
@sandydoo  That's quite sad. I do like the idea of the `clean` feature.. I am trying to launch something inside a devenv - and it does work on all of my machines but on some other machines it does not. Except if they use `devenv -c`.. That's why I wanted to add `clean: true`.

but if `clean` is not meant to be used it should maybe be removed?

**Comment by sandydoo** [comment] 2024-10-02 11:54
> but on some other machines it does not.

Do you have an idea what it is? That is generally something we'd be interested in hearing about and fixing.

> but if clean is not meant to be used it should maybe be removed?

Yeah, so it's an option that's passed down to `nix develop`. Some people didn't like the "noise" that `nix develop` adds to the shell, so this option was exposed. We ended up inheriting its issues. There's will to fix it, just not while we continue to use `nix develop`.

**Comment by Enteee** [comment] 2024-10-02 12:18
> Do you have an idea what it is? That is generally something we'd be interested in hearing about and fixing.

If I'd know this i would probably have fixed it already ;) I am bubbelwrapping chromium to fake a `/etc/hosts`.. And in the process of that chromium fails to with:

```
[2:2:0930/170447.244416:ERROR:process_singleton_posix.cc(1057)] Failed to create socket directory.
[2:2:0930/170447.244549:ERROR:chrome_main_delegate.cc(597)] Failed to create a ProcessSingleton for your profile directory. This means that running multiple instances would start multiple browser processes rather than opening a new window in the existing process. Aborting now to avoid profile corruption.
```

But I have not yet found out why this does not work on any system..

> Yeah, so it's an option that's passed down to nix develop. Some people didn't like the "noise" that nix develop adds to the shell, so this option was exposed. We ended up inheriting its issues. There's will to fix it, just not while we continue to use nix develop.

ack.

**Comment by dacevedo12** [comment] 2025-02-11 20:41
Figured it out, for posterity:

```
clean:
  enabled: true
  keep:
    - HOME
    - TERM
```

Keeping HOME is necessary for this reason https://github.com/F1bonacc1/process-compose/issues/175#issuecomment-2081178518, otherwise it will try to write `mkdir /Library/Application Support/process-compose` and get access denied.

Keeping TERM is necessary for this reason https://github.com/F1bonacc1/process-compose/issues/173#issuecomment-2043747974

You will also need to include `pkgs.ncurses` in your devenv.nix packages, otherwise it will fail for the reason mentioned in this issue: `exec: "infocmp": executable file not found in $PATH`
