### ISSUE TITLE
Missing Cargo.lock error when updating devenv

### ISSUE THREAD

**Issue by mbainter** [cachix/devenv#1473] opened 2024-09-25 04:06 UTC
**Describe the bug**

I got an error running devenv update, and when I popped into discord there was someone else with the same error, so I do not believe it is unique to my environment. I tried creating a new devenv as a test and it throws the same error.

**To reproduce**
1. Install devenv 1.1.0
2. run `devenv init` in a fresh directory

<details>
<summary>The process fails with a missing Cargo.lock for diffutils-3.10</summary>
<p>

```
devenv 1.0.8 (x86_64-linux)
direnv: loading ~/tmp/test/.envrc
direnv: loading https://raw.githubusercontent.com/cachix/devenv/95f329d49a8a5289d31e0982652f7058a189bfca/direnvrc (sha256-d+8cBpDfDBj41inrADaJt+bDWhOktwslgoP5YiGJ1v0=)
direnv: using devenv
direnv: .envrc changed, reloading
direnv: ([/nix/store/ic11r65mm23k23jf6k1bcnvxwssl4sk7-direnv-2.34.0/bin/direnv export bash]) is taking a while to execute. Use CTRL-C to give up.
• Using Cachix: devenv
error: builder for '/nix/store/b1zc3760hsxywcb4drycqg82fyg8h8qj-devenv-1.2.drv' failed with exit code 1;
       last 10 log lines:
       > unpacking source archive /nix/store/0ccnxa25whszw7mgbgyzdm4nqc0zwnm8-source
       > source root is source
       > Executing cargoSetupPostUnpackHook
       > Finished cargoSetupPostUnpackHook
       > Running phase: patchPhase
       > Executing cargoSetupPostPatchHook
       > Validating consistency between /build/source/Cargo.lock and /build/cargo-vendor-dir/Cargo.lock
       > /nix/store/ksyif7fp4p0baafvdm5szd375s7qf6cz-diffutils-3.10/bin/diff: /build/source/Cargo.lock: No such file or directory
       > ERROR: Missing Cargo.lock from src. Expected to find it at: /build/source/Cargo.lock
       > Hint: You can use the cargoPatches attribute to add a Cargo.lock manually to the build.
       For full logs, run 'nix log /nix/store/b1zc3760hsxywcb4drycqg82fyg8h8qj-devenv-1.2.drv'.
error:
       error: 1 dependencies of derivation '/nix/store/bc5z7n81s0wzb1ankz2j5di8vwqvgy5i-devenv-shell-env.drv' failed to build

✖ Command produced the following output:


Error:   × Command `/nix/store/abzmhqk4z6a8jqk2k532almj0gl33f8k-nix-2.21-devenv/bin/nix --show-trace --extra-experimental-features nix-command --extra-experimental-
  │ features flakes --option warn-dirty false --keep-going --max-jobs 10 --option eval-cache false print-dev-env --profile /home/mbainter/tmp/test/.devenv/gc/shell
  │ --option extra-substituters https://devenv.cachix.org --option extra-trusted-public-keys nixpkgs-python.cachix.org-1:hxjI7pFxTyuTHn2NkvWCrAUcNZLNS3ZAvfYNuYifcEU=
  │ devenv.cachix.org-1:w1cLUi8dv3hnoSPGAuibQv+f9TZLr6cv/Hm9XgU50cw=` failed with with exit code 1

direnv: failed to build the devenv environment. devenv.nix may contain errors. see above
```

</p>
</details>

**Version**

devenv 1.1.0 (x86_64-linux)

**Comment by mbainter** [comment] 2024-09-25 04:21
I have fixed it, but frustratingly I'm not 100% sure what it was.  I hadn't updated in a bit, so I kicked that process off and then went back to that directory to poke around a little more.  I'd already tried a fresh shell but this time it prompted me for the .envrc changing.  I approved that, and it ran cleanly. After that, a `direnv update` also completed successfully.

So if you land here because you're seeing the same thing, kick off a fresh shell, then see if you get a direnv allow.  If not, perhaps try running it anyway to try to get it to load the updated reference.

If that doesn't work, and you're running nix, try updating your NIXOS and/or homedir and try again. Maybe you'll be able to narrow down the exact resolution to the issue.

**Comment by MarceColl** [comment] 2024-09-25 05:07
Can you reopen the issue? It is not solved in general and would be nice to know what happened. If it's marked as completed we'll probably never know

**Comment by domenkozar** [comment] 2024-09-25 16:41
I can't reproduce this:

```
❯ devenv version
devenv 1.1.0 (x86_64-linux)

~/dev via λ 
❯ devenv init foo2
• Creating devenv.nix
• Creating devenv.yaml
• Creating .envrc
• Creating .gitignore

~/dev via λ 
❯ cd foo2
direnv: loading ~/dev/foo2/.envrc
direnv: loading https://raw.githubusercontent.com/cachix/devenv/95f329d49a8a5289d31e0982652f7058a189bfca/direnvrc (sha256-d+8cBpDfDBj41inrADaJt+bDWhOktwslgoP5YiGJ1v0=)
direnv: using devenv
direnv: .envrc changed, reloading
• Using Cachix: devenv
direnv: updated devenv shell cache
Running tasks     devenv:enterShell

Succeeded         devenv:enterShell 3ms
1 Succeeded                         51.65ms

hello from devenv
git version 2.44.0
``

**Comment by MarceColl** [comment] 2024-09-25 18:05
I think there was a particular version of nixpkgs that had something broken, after doing

```
nix flake update
nixos-rebuild switch
```

**Comment by sandydoo** [comment] 2024-09-26 14:29
This should hopefully be fixed as of https://github.com/cachix/devenv/commit/ebd3f5f20a520bf948b143262c96fc59f412e0b3.

**Closed** 2024-10-04 17:45 UTC
Labels: bug
