### ISSUE TITLE
Allow detached `devenv up`

### ISSUE THREAD

**Issue by mweinelt** [cachix/devenv#524] opened 2023-04-07 22:46 UTC
Sometimes I want services to start with `devenv up`, and then continue working in that shell.

What I would imagine would be that I can
- Run `devenv up --detach` and it will start processes in the background
- Run `devenv down` to stop these processes

Basically like `docker compose` does it.

**Comment by wannevancamp** [comment] 2023-05-14 20:06
Seems related to https://github.com/cachix/devenv/pull/83 or [this discussion ](https://github.com/F1bonacc1/process-compose/discussions/35). Very interested in this feature.

**Comment by stig** [comment] 2023-06-20 10:34
Seems like a duplicate of https://github.com/cachix/devenv/issues/80 too.

**Comment by domenkozar** [comment] 2023-06-30 10:36
Closing as a duplicate.

**Closed by domenkozar** 2023-06-30 10:36 UTC
