### ISSUE TITLE
Unable to `devenv up` on a fresh flake template install.

### ISSUE THREAD

**Issue by natecox** [cachix/devenv#864] opened 2023-11-06 19:55 UTC
**Describe the bug**
On a fresh install of devenv, I am unable to `devenv up`. I may be fundamentally misunderstanding the use pattern here and I would appreciate being pointed in the correct direction. Gist below contains my command log with outputs and the flake.nix generated by the template.

When I attempt to `devenv up` I get:
```error: flake 'path:/Users/ncox/src/natecox/direnv_test' does not provide attribute 'packages.aarch64-darwin.devenv-up', 'legacyPackages.aarch64-darwin.devenv-up' or 'devenv-up'```

Perhaps relevant, I'm on a MacBook Pro with an M1 chip, which is why it's looking for `aarch64-darwin`.

**To reproduce**
https://gist.github.com/natecox/d695aaf63908feaca99c9e9641268896

**Version** 
devenv: 0.6.3

**Comment by natecox** [comment] 2023-11-07 17:53
Update, the "flake.parts" instructions do seem to provide `devenv up`. I'm not actually sure what the difference is between flakes and flake parts, but when I change the template to the parts one I'm able to get everything working  ¯\_(ツ)_/¯.

**Comment by B4mbus** [comment] 2023-11-12 17:36
Same situation for me. Additionally, the flake-parts template doesn't provide any .envrc, the ordinary flake one does.

**Comment by sandydoo** [comment] 2023-11-13 19:42
Duplicate of #756?

**Comment by natecox** [comment] 2023-11-13 23:01
Yep, looks like a duplicate. I didn’t find that one when I went looking.

**Closed** 2023-11-16 09:40 UTC
Labels: bug

**Comment by sandydoo** [comment] 2023-11-16 10:06
> When I attempt to devenv up I get:
error: flake 'path:/Users/ncox/src/natecox/direnv_test' does not provide attribute 'packages.aarch64-darwin.devenv-up', 'legacyPackages.aarch64-darwin.devenv-up' or 'devenv-up'

I've updated the template with an interim fix. We'll try to create a unified story for flake integration in or after the 1.0 release.

> I'm not actually sure what the difference is between flakes and flake parts

[Flake Parts](https://flake.parts/) is an opinionated library for writing flakes. The goal is to make flakes more modular (with modules) and to improve the user experience of writing and maintaining flakes.

> Additionally, the flake-parts template doesn't provide any .envrc, the ordinary flake one does.

Thanks! Fixed in #874.
